### ISSUE TITLE
lesson links point to old locations

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/genome-mining-workshop#1]
The links to lessons in the workshop overview table point to their old locations, before the lessons were transferred into the Incubator. These should be updated here, but you might also want to create placeholder repositories in the old locations that will redirect people using the old URL to the lesson site at its new location. See https://github.com/carpentrieslab/python-aos-lesson for an example of a repository created to redirect people to a GitHub Pages site that has moved.

**Comment by nselem** [comment]
Thank Toby. Links have been updated to the carpentries-incubator's new location.
